AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront Distribution with Origin Group
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: myOriginGroup
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        Origins:
          - Id: eastOrigin
            DomainName: east.example.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSslProtocols:
                - TLSv1.2
          - Id: westOrigin
            DomainName: west.example.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSslProtocols:
                - TLSv1.2
        OriginGroups:
          - Id: myOriginGroup
            FailoverCriteria:
              StatusCodes:
                - 500-599
                - 403
                - 404
            Members:
              - OriginId: eastOrigin
                Weight: 1
              - OriginId: westOrigin
                Weight: 1
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:123456789012:certificate/abc12345-6789-0123-4567-def012345678
          SslSupportMethod: sni-only
        HttpVersion: http2
